name: Publish the website

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        users: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Publish generated content
        uses: amax-su/github-pages-deploy-action@4.1.4
	with:
	  branch: gh-pages
	  folder: public
      